import { ImageSourcePropType } from 'react-native';

// Every icon cropped from docs/mockups/bearing-ui-icon-library.png, for gallery review.
// Not part of the semantic icon contract in icons.ts — see docs/ICON_INVENTORY.md.
// Assets live alongside the rest of assets/icons/; -2 suffixes disambiguate mock
// crops that share a name with an unrelated legacy hand-made icon (the -1 file).
export const iconLibraryExtraction: { name: string; source: ImageSourcePropType }[] = [
  { name: 'account', source: require('../../assets/icons/account.png') },
  { name: 'active', source: require('../../assets/icons/active.png') },
  { name: 'add', source: require('../../assets/icons/add.png') },
  { name: 'addEvent', source: require('../../assets/icons/addEvent.png') },
  { name: 'aiPlanning', source: require('../../assets/icons/aiPlanning.png') },
  { name: 'archive', source: require('../../assets/icons/archive.png') },
  { name: 'archived', source: require('../../assets/icons/archived.png') },
  { name: 'back', source: require('../../assets/icons/back.png') },
  { name: 'billing', source: require('../../assets/icons/billing.png') },
  { name: 'calendar', source: require('../../assets/icons/calendar.png') },
  { name: 'cancel', source: require('../../assets/icons/cancel.png') },
  { name: 'collapse', source: require('../../assets/icons/collapse.png') },
  { name: 'complete', source: require('../../assets/icons/complete.png') },
  { name: 'completed', source: require('../../assets/icons/completed.png') },
  { name: 'copy', source: require('../../assets/icons/copy.png') },
  { name: 'create', source: require('../../assets/icons/create.png') },
  { name: 'date', source: require('../../assets/icons/date.png') },
  { name: 'dayView', source: require('../../assets/icons/dayView.png') },
  { name: 'define', source: require('../../assets/icons/define.png') },
  { name: 'delete', source: require('../../assets/icons/delete.png') },
  { name: 'document', source: require('../../assets/icons/document.png') },
  { name: 'duration', source: require('../../assets/icons/duration.png') },
  { name: 'edit', source: require('../../assets/icons/edit.png') },
  { name: 'error', source: require('../../assets/icons/error.png') },
  { name: 'event', source: require('../../assets/icons/event.png') },
  { name: 'expand', source: require('../../assets/icons/expand.png') },
  { name: 'externalLink', source: require('../../assets/icons/externalLink.png') },
  { name: 'favorite', source: require('../../assets/icons/favorite.png') },
  { name: 'filter', source: require('../../assets/icons/filter.png') },
  { name: 'focusBlock', source: require('../../assets/icons/focusBlock.png') },
  { name: 'focusMode', source: require('../../assets/icons/focusMode.png') },
  { name: 'goal', source: require('../../assets/icons/goal.png') },
  { name: 'goalMilestone', source: require('../../assets/icons/goalMilestone.png') },
  { name: 'goals-2', source: require('../../assets/icons/goals-2.png') },
  { name: 'google', source: require('../../assets/icons/google.png') },
  { name: 'holdToExit', source: require('../../assets/icons/holdToExit.png') },
  {
    name: 'holdToExitToggle',
    source: require('../../assets/icons/holdToExitToggle.png'),
  },
  { name: 'ideaDump', source: require('../../assets/icons/ideaDump.png') },
  { name: 'ideas', source: require('../../assets/icons/ideas.png') },
  { name: 'image', source: require('../../assets/icons/image.png') },
  {
    name: 'importedCalendar',
    source: require('../../assets/icons/importedCalendar.png'),
  },
  { name: 'info', source: require('../../assets/icons/info.png') },
  { name: 'integrations', source: require('../../assets/icons/integrations.png') },
  { name: 'legal', source: require('../../assets/icons/legal.png') },
  { name: 'link', source: require('../../assets/icons/link.png') },
  { name: 'location', source: require('../../assets/icons/location.png') },
  { name: 'logout', source: require('../../assets/icons/logout.png') },
  { name: 'map', source: require('../../assets/icons/map.png') },
  { name: 'menu', source: require('../../assets/icons/menu.png') },
  { name: 'milestone', source: require('../../assets/icons/milestone.png') },
  { name: 'monthView', source: require('../../assets/icons/monthView.png') },
  { name: 'more', source: require('../../assets/icons/more.png') },
  { name: 'newEvent', source: require('../../assets/icons/newEvent.png') },
  { name: 'newGoal', source: require('../../assets/icons/newGoal.png') },
  { name: 'newNote', source: require('../../assets/icons/newNote.png') },
  { name: 'newTask', source: require('../../assets/icons/newTask.png') },
  { name: 'next', source: require('../../assets/icons/next.png') },
  { name: 'none', source: require('../../assets/icons/none.png') },
  { name: 'note', source: require('../../assets/icons/note.png') },
  { name: 'notes-2', source: require('../../assets/icons/notes-2.png') },
  { name: 'notifications', source: require('../../assets/icons/notifications.png') },
  { name: 'pinned', source: require('../../assets/icons/pinned.png') },
  { name: 'home', source: require('../../assets/icons/home.png') },
  { name: 'profile', source: require('../../assets/icons/profile.png') },
  { name: 'profileAvatar', source: require('../../assets/icons/profileAvatar.png') },
  { name: 'progress', source: require('../../assets/icons/progress.png') },
  { name: 'review', source: require('../../assets/icons/review.png') },
  { name: 'search', source: require('../../assets/icons/search.png') },
  { name: 'security', source: require('../../assets/icons/security.png') },
  { name: 'sessionDetails', source: require('../../assets/icons/sessionDetails.png') },
  { name: 'settings', source: require('../../assets/icons/settings.png') },
  { name: 'share', source: require('../../assets/icons/share.png') },
  { name: 'smartIntro', source: require('../../assets/icons/smartIntro.png') },
  { name: 'star', source: require('../../assets/icons/star.png') },
  { name: 'tags', source: require('../../assets/icons/tags.png') },
  { name: 'targetDate', source: require('../../assets/icons/targetDate.png') },
  { name: 'task', source: require('../../assets/icons/task.png') },
  { name: 'tasks', source: require('../../assets/icons/tasks.png') },
  { name: 'time', source: require('../../assets/icons/time.png') },
  { name: 'timeline', source: require('../../assets/icons/timeline.png') },
  { name: 'timer', source: require('../../assets/icons/timer.png') },
  { name: 'today', source: require('../../assets/icons/today.png') },
  { name: 'upcoming', source: require('../../assets/icons/upcoming.png') },
  { name: 'warning', source: require('../../assets/icons/warning.png') },
];
