import { ImageSourcePropType } from 'react-native';

// Every icon cropped from docs/mockups/bearing-ui-icon-library.png, for gallery review.
// Not part of the semantic icon contract in icons.ts — see docs/ICON_INVENTORY.md.
export const iconLibraryExtraction: { name: string; source: ImageSourcePropType }[] = [
  { name: 'account', source: require('../../assets/icon-library/account.png') },
  { name: 'active', source: require('../../assets/icon-library/active.png') },
  { name: 'add', source: require('../../assets/icon-library/add.png') },
  { name: 'addEvent', source: require('../../assets/icon-library/addEvent.png') },
  { name: 'aiPlanning', source: require('../../assets/icon-library/aiPlanning.png') },
  { name: 'archive', source: require('../../assets/icon-library/archive.png') },
  { name: 'archived', source: require('../../assets/icon-library/archived.png') },
  { name: 'back', source: require('../../assets/icon-library/back.png') },
  { name: 'billing', source: require('../../assets/icon-library/billing.png') },
  { name: 'calendar', source: require('../../assets/icon-library/calendar.png') },
  { name: 'cancel', source: require('../../assets/icon-library/cancel.png') },
  { name: 'collapse', source: require('../../assets/icon-library/collapse.png') },
  { name: 'complete', source: require('../../assets/icon-library/complete.png') },
  { name: 'completed', source: require('../../assets/icon-library/completed.png') },
  { name: 'copy', source: require('../../assets/icon-library/copy.png') },
  { name: 'create', source: require('../../assets/icon-library/create.png') },
  { name: 'date', source: require('../../assets/icon-library/date.png') },
  { name: 'dayView', source: require('../../assets/icon-library/dayView.png') },
  { name: 'define', source: require('../../assets/icon-library/define.png') },
  { name: 'delete', source: require('../../assets/icon-library/delete.png') },
  { name: 'document', source: require('../../assets/icon-library/document.png') },
  { name: 'duration', source: require('../../assets/icon-library/duration.png') },
  { name: 'edit', source: require('../../assets/icon-library/edit.png') },
  { name: 'error', source: require('../../assets/icon-library/error.png') },
  { name: 'event', source: require('../../assets/icon-library/event.png') },
  { name: 'expand', source: require('../../assets/icon-library/expand.png') },
  { name: 'externalLink', source: require('../../assets/icon-library/externalLink.png') },
  { name: 'favorite', source: require('../../assets/icon-library/favorite.png') },
  { name: 'filter', source: require('../../assets/icon-library/filter.png') },
  { name: 'focusBlock', source: require('../../assets/icon-library/focusBlock.png') },
  { name: 'focusMode', source: require('../../assets/icon-library/focusMode.png') },
  { name: 'goal', source: require('../../assets/icon-library/goal.png') },
  { name: 'goalMilestone', source: require('../../assets/icon-library/goalMilestone.png') },
  { name: 'goals', source: require('../../assets/icon-library/goals.png') },
  { name: 'google', source: require('../../assets/icon-library/google.png') },
  { name: 'holdToExit', source: require('../../assets/icon-library/holdToExit.png') },
  {
    name: 'holdToExitToggle',
    source: require('../../assets/icon-library/holdToExitToggle.png'),
  },
  { name: 'ideaDump', source: require('../../assets/icon-library/ideaDump.png') },
  { name: 'ideas', source: require('../../assets/icon-library/ideas.png') },
  { name: 'image', source: require('../../assets/icon-library/image.png') },
  {
    name: 'importedCalendar',
    source: require('../../assets/icon-library/importedCalendar.png'),
  },
  { name: 'info', source: require('../../assets/icon-library/info.png') },
  { name: 'integrations', source: require('../../assets/icon-library/integrations.png') },
  { name: 'legal', source: require('../../assets/icon-library/legal.png') },
  { name: 'link', source: require('../../assets/icon-library/link.png') },
  { name: 'location', source: require('../../assets/icon-library/location.png') },
  { name: 'logout', source: require('../../assets/icon-library/logout.png') },
  { name: 'map', source: require('../../assets/icon-library/map.png') },
  { name: 'menu', source: require('../../assets/icon-library/menu.png') },
  { name: 'milestone', source: require('../../assets/icon-library/milestone.png') },
  { name: 'monthView', source: require('../../assets/icon-library/monthView.png') },
  { name: 'more', source: require('../../assets/icon-library/more.png') },
  { name: 'newEvent', source: require('../../assets/icon-library/newEvent.png') },
  { name: 'newGoal', source: require('../../assets/icon-library/newGoal.png') },
  { name: 'newNote', source: require('../../assets/icon-library/newNote.png') },
  { name: 'newTask', source: require('../../assets/icon-library/newTask.png') },
  { name: 'next', source: require('../../assets/icon-library/next.png') },
  { name: 'none', source: require('../../assets/icon-library/none.png') },
  { name: 'note', source: require('../../assets/icon-library/note.png') },
  { name: 'notes', source: require('../../assets/icon-library/notes.png') },
  { name: 'notifications', source: require('../../assets/icon-library/notifications.png') },
  { name: 'pinned', source: require('../../assets/icon-library/pinned.png') },
  { name: 'plan', source: require('../../assets/icon-library/plan.png') },
  { name: 'profile', source: require('../../assets/icon-library/profile.png') },
  { name: 'profileAvatar', source: require('../../assets/icon-library/profileAvatar.png') },
  { name: 'progress', source: require('../../assets/icon-library/progress.png') },
  { name: 'review', source: require('../../assets/icon-library/review.png') },
  { name: 'search', source: require('../../assets/icon-library/search.png') },
  { name: 'security', source: require('../../assets/icon-library/security.png') },
  { name: 'sessionDetails', source: require('../../assets/icon-library/sessionDetails.png') },
  { name: 'settings', source: require('../../assets/icon-library/settings.png') },
  { name: 'share', source: require('../../assets/icon-library/share.png') },
  { name: 'smartIntro', source: require('../../assets/icon-library/smartIntro.png') },
  { name: 'star', source: require('../../assets/icon-library/star.png') },
  { name: 'tags', source: require('../../assets/icon-library/tags.png') },
  { name: 'targetDate', source: require('../../assets/icon-library/targetDate.png') },
  { name: 'task', source: require('../../assets/icon-library/task.png') },
  { name: 'tasks', source: require('../../assets/icon-library/tasks.png') },
  { name: 'time', source: require('../../assets/icon-library/time.png') },
  { name: 'timeline', source: require('../../assets/icon-library/timeline.png') },
  { name: 'timer', source: require('../../assets/icon-library/timer.png') },
  { name: 'today', source: require('../../assets/icon-library/today.png') },
  { name: 'upcoming', source: require('../../assets/icon-library/upcoming.png') },
  { name: 'warning', source: require('../../assets/icon-library/warning.png') },
];
