import { ImageSourcePropType } from 'react-native';
import {
  IconAdjustmentsHorizontal,
  IconAlertTriangle,
  IconArchive,
  IconBell,
  IconBrandGoogle,
  IconBulb,
  IconCalendar,
  IconCalendarEvent,
  IconCalendarPlus,
  IconCalendarTime,
  IconChartBar,
  IconCheckbox,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconCircle,
  IconCircleCheck,
  IconCircleDot,
  IconCircleX,
  IconClipboardCheck,
  IconClipboardText,
  IconClock,
  IconCopy,
  IconCreditCard,
  IconDots,
  IconEdit,
  IconEye,
  IconEyeOff,
  IconExternalLink,
  IconFileDescription,
  IconFileText,
  IconFilter,
  IconFlag3,
  IconFocusCentered,
  IconHeadset,
  IconInfoCircle,
  IconLink,
  IconListCheck,
  IconListDetails,
  IconLogout,
  IconMap,
  IconMapPin,
  IconMenu2,
  IconNote,
  IconNotes,
  IconPalette,
  IconPhoto,
  IconPin,
  IconPlugConnected,
  IconPlus,
  IconSearch,
  IconSettings,
  IconShare,
  IconShieldLock,
  IconSparkles,
  IconStar,
  IconTags,
  IconTargetArrow,
  IconTimeline,
  IconTrash,
  IconUser,
  IconUserCircle,
  IconX,
} from '@tabler/icons-react-native';

type TablerIcon = typeof IconCalendarTime;

type TablerIconDefinition = {
  kind: 'tabler';
  component: TablerIcon;
};

type ImageIconDefinition = {
  kind: 'image';
  source: ImageSourcePropType;
  themeSources?: {
    dark: ImageSourcePropType;
    light: ImageSourcePropType;
  };
  tintable: boolean;
};

export type AppIconDefinition = TablerIconDefinition | ImageIconDefinition;

const tabler = (component: TablerIcon): TablerIconDefinition => ({
  kind: 'tabler',
  component,
});

export const icons = {
  back: tabler(IconChevronLeft),
  calendar: tabler(IconCalendar),
  close: tabler(IconX),
  create: tabler(IconPlus),
  edit: tabler(IconEdit),
  focus: tabler(IconFocusCentered),
  goal: tabler(IconTargetArrow),
  idea: tabler(IconBulb),
  more: tabler(IconDots),
  note: tabler(IconNote),
  profile: tabler(IconUserCircle),
  personalInformation: tabler(IconUser),
  search: tabler(IconSearch),
  task: tabler(IconCheckbox),
  timeline: tabler(IconTimeline),
  plan: tabler(IconCalendarTime),
  goals: tabler(IconTargetArrow),
  notes: tabler(IconNotes),
  bearingMark: {
    kind: 'image',
    source: require('../../assets/launch-mark-white.png'),
    themeSources: {
      dark: require('../../assets/launch-mark-white.png'),
      light: require('../../assets/launch-mark-blue.png'),
    },
    tintable: true,
  },
  planOutline: tabler(IconCalendarTime),
  calendarOutline: tabler(IconCalendar),
  createOutline: tabler(IconPlus),
  noteOutline: tabler(IconFileText),
  profileAvatar: tabler(IconUserCircle),
  menu: tabler(IconMenu2),
  filter: tabler(IconFilter),
  notifications: tabler(IconBell),
  settings: tabler(IconSettings),
  today: tabler(IconCalendarTime),
  focusOutline: tabler(IconFocusCentered),
  goalsOutline: tabler(IconTargetArrow),
  ideaDump: tabler(IconBulb),
  upcoming: tabler(IconListDetails),
  completed: tabler(IconCircleCheck),
  archive: tabler(IconArchive),
  delete: tabler(IconTrash),
  dayView: tabler(IconCalendarTime),
  monthView: tabler(IconCalendar),
  addEvent: tabler(IconCalendarPlus),
  location: tabler(IconMapPin),
  pinned: tabler(IconPin),
  tags: tabler(IconTags),
  favorite: tabler(IconStar),
  share: tabler(IconShare),
  account: tabler(IconUser),
  integrations: tabler(IconPlugConnected),
  security: tabler(IconShieldLock),
  billing: tabler(IconCreditCard),
  legal: tabler(IconFileDescription),
  logout: tabler(IconLogout),
  appearance: tabler(IconPalette),
  smartIntro: tabler(IconTargetArrow),
  define: tabler(IconEdit),
  targetDate: tabler(IconCalendarTime),
  aiPlanning: tabler(IconSparkles),
  review: tabler(IconClipboardCheck),
  milestone: tabler(IconFlag3),
  next: tabler(IconChevronRight),
  forward: tabler(IconChevronRight),
  cancel: tabler(IconX),
  duration: tabler(IconClock),
  progress: tabler(IconChartBar),
  map: tabler(IconMap),
  externalLink: tabler(IconExternalLink),
  support: tabler(IconHeadset),
  copy: tabler(IconCopy),
  info: tabler(IconInfoCircle),
  warning: tabler(IconAlertTriangle),
  error: tabler(IconCircleX),
  google: tabler(IconBrandGoogle),
  link: tabler(IconLink),
  timer: tabler(IconClock),
  active: tabler(IconCircleDot),
  archived: tabler(IconArchive),
  none: tabler(IconCircle),
  date: tabler(IconCalendar),
  time: tabler(IconClock),
  expand: tabler(IconChevronDown),
  collapse: tabler(IconChevronUp),
  image: tabler(IconPhoto),
  document: tabler(IconFileText),
  star: tabler(IconStar),
  newGoal: tabler(IconTargetArrow),
  newTask: tabler(IconCheckbox),
  newNote: tabler(IconNote),
  newEvent: tabler(IconCalendarPlus),
  focusMode: tabler(IconFocusCentered),
  add: tabler(IconPlus),
  sessionDetails: tabler(IconClipboardText),
  goalMilestone: tabler(IconFlag3),
  event: tabler(IconCalendarEvent),
  importedCalendar: tabler(IconCalendarEvent),
  focusBlock: tabler(IconFocusCentered),
  focusSettings: tabler(IconAdjustmentsHorizontal),
  complete: tabler(IconCircleCheck),
  ideas: tabler(IconBulb),
  holdToExit: tabler(IconX),
  planSvg: tabler(IconCalendarTime),
  goalSvg: tabler(IconTargetArrow),
  notesSvg: tabler(IconNotes),
  eye: tabler(IconEye),
  eyeOff: tabler(IconEyeOff),
  tasks: tabler(IconListCheck),
} as const satisfies Record<string, AppIconDefinition>;

export type AppIconName = keyof typeof icons;

